### ISSUE TITLE
有移动端能用的吗？支持上滑分页和下拉刷新的吗？

### ISSUE THREAD

**Issue by sir-ran** [linpengteng/vue-sticker-table#1]
有移动端能用的吗？支持上滑分页和下拉刷新的吗？

**Comment by linpengteng** [comment]
因为无需第三方组件库，可以支持移动端。但没有上滑分页和下拉刷新这部分功能，需要单独实现分页组件功能，可参考[https://github.com/linpengteng/vue-sticker-table/tree/main/example/components/TablePagination](url)
